### ISSUE TITLE
借地请教：gsi是否存在无法通话的问题

### ISSUE THREAD

**Issue by ivysrono** [D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP#10]
XAGA
中国电信
刷入GSI（包括PHH和Google）
通话无法听到对方声音——单向问题，对方可以听到己方声音。
D1100上未发现此问题。
不知有无解决方案或者思路。

**Comment by ivysrono** [comment]
找到酷安才发现是通病了。 现在刷机还是在酷安这种封闭的地方么……

**Comment by sopy264** [comment]
有没有一种可能，咱修了

**Comment by sopy264** [comment]
（至少在我们做出的rom是的

**Comment by ivysrono** [comment]
正在下载你们做的PEP和evoX。
自从用上GSI，早就不用TWRP了，再看到你们那一串风险提示，有点虚啊……

**Comment by ivysrono** [comment]
成功刷上0727版PEP，通话终于正常啦，非常感谢！
话说，这个通话补丁有可能将来移植到GSI不？
@wbs306 @sopy264

**Comment by ivysrono** [comment]
@wbs306 还是借地反馈bug：https://github.com/aki65/aki65.github.io/issues/67
GSI里闪过几下还会正确显示的，PEP问题严重化了。

**Comment by wbs306** [comment]
这个问题我之后看看，因为状态栏在b站上也有问题。另外这里是twrp的仓库，维护者不止我一个，还是建议到device tree那边重开一个issue。
