### ISSUE TITLE
深受其害，启动卡B槽，真得深刷了

### ISSUE THREAD

**Issue by EASTINK** [D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP#13]
应在Readme告知实际已不适用现在的MIUI14版本。（钱包空空，痛哭流涕

**Comment by YuKongA** [comment]
![image](https://github.com/dimensity-twrp-dev/device_xiaomi_xaga-TWRP/assets/70465933/0694f9fb-92e6-4f4b-95b1-d8ffe50dbe01)
目前分支能引导版本: 5.10.66 内核版本
