### ISSUE TITLE
features bug

### ISSUE THREAD

**Issue by sopy264** [D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP#4]
解密data功能无法正常使用

**Comment by YuKongA** [comment]
解密在 k50 上工作正常，可以尝试替换下 xaga 自己的解密相关文件试试，我看过 xaga 的 dump，解密过程应该是一样的。

**Comment by wbs306** [comment]
> 解密在 k50 上工作正常，可以尝试替换下 xaga 自己的解密相关文件试试，我看过 xaga 的 dump，解密过程应该是一样的。

看了一下 `vendor/thh/ta` 确实是有几个文件不一样，就是那个 `microtrust.rc` 里面的用户组不太一样，不知道是否需要替换：
```
diff device_xiaomi_xaga-TWRP/recovery/root/microtrust.rc miui_XAGA_V13.0.9.0.SLOCNXM_8b3cec057f_12.0/vendor/etc/init/microtrust.rc

24,25c24,26
<     user root
<     group root
---
>     class core
>     user system
>     group system
27c28,29
<     seclabel u:r:recovery:s0
---
>     capabilities SYS_RAWIO
>    # oneshot
245a248
> 
```

**Comment by YuKongA** [comment]
用户组权限是特意修改成这样的

**Comment by wbs306** [comment]
那就没啥要换的了

**Comment by YuKongA** [comment]
K50Pro 那边倒是正常🤔

**Comment by sopy264** [comment]
怪

**Comment by sopy264** [comment]
(我因为没有设置密码所以没有加密，提出者是酷友desu

**Comment by wbs306** [comment]
这几个文件是主要差异
![image](https://user-images.githubusercontent.com/10919115/175807217-f383d4e5-735d-42c9-ab1f-3fcec3019d90.png)
那个 `gatekeeper.default.so` 是软连接到了 `lib64/libSoftGatekeeper.so`，`lib64/hw` 里另外有一个 `gatekeeper.beanpod.so`

**Comment by YuKongA** [comment]
都是一样的结构，全部换 xaga 自己的试试吧。我昨天看了上个 issue 的 log，服务应该是都跑起来了的。

**Comment by wbs306** [comment]
ok, 等过几天手机解锁（

**Comment by YuKongA** [comment]
更新了下 thh ，我在 workflows 跑了个 ci ，大概2小时之后能出来。 @sopy264 到时候试试解密吧。

**Comment by sopy264** [comment]
在新的actions中此功能得到了实现
