### ISSUE TITLE
最新开发版miui似乎无法使用

### ISSUE THREAD

**Issue by sopy264** [D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP#5]
0.9版本的note 11tpro/pro+用户认证有两人反馈刷入最新开发版miui后砖，也许该考虑考虑新版本适配(不过开发版嘛，后面再去适配应该也没关系)(V13.0.4.1.39.DEV )

**Comment by YuKongA** [comment]
开发板更新了 5.10.81

**Comment by YuKongA** [comment]
联发科真不建议主力玩机，特别容易砖。要是以前倒还好，深刷能绕过权限，现在深刷不能自己来不说，联发科深刷工具对动态分区的支持还不好。另外说个题外话，联发科深刷权限漏洞的修补是小米提交的😥

**Comment by wbs306** [comment]
> 联发科真不建议主力玩机，特别容易砖。要是以前倒还好，深刷能绕过权限，现在深刷不能自己来不说，联发科深刷工具对动态分区的支持还不好。另外说个题外话，联发科深刷权限漏洞的修补是小米提交的😥

？？？啊这，感觉现在小米可玩性远没有以前高了，大半年也不开内核源码。

另外现在已知twrp可以刷我先前编译好的EvolutionX，不知道是不是因为开发版中有其他分区文件导致刷机失败。（或者应该还是vab的锅？）

**Comment by sopy264** [comment]
天知道刷的哪个slot，估计以后测试顶多，不过测一台废一台🌚

**Comment by sopy264** [comment]
> > 联发科真不建议主力玩机，特别容易砖。要是以前倒还好，深刷能绕过权限，现在深刷不能自己来不说，联发科深刷工具对动态分区的支持还不好。另外说个题外话，联发科深刷权限漏洞的修补是小米提交的😥
> 
> ？？？啊这，感觉现在小米可玩性远没有以前高了，大半年也不开内核源码。
> 
> 另外现在已知twrp可以刷我先前编译好的EvolutionX，不知道是不是因为开发版中有其他分区文件导致刷机失败。（或者应该还是vab的锅？）

我估计应该是可能是因为我刷了slot b，具体我也不知道

**Comment by sopy264** [comment]
是酷安友人刷坏哩.jpg
